services:
  frontend:
    build:
      context: .
      dockerfile: ./docker/Dockerfile.staging
    ports:
      - "8003:80"
    restart: always
    logging:
      driver: "json-file"
      options:
        max-size: "50m"
        max-file: "3"




